### ISSUE TITLE
图片纹理只显示四分之一

### ISSUE THREAD

**Issue by SongJiaqiang** [icetime17/DemoOpenGL#2]
你好！按照文章[OpenGLES之图片纹理](http://icetime17.github.io/2016/03/27/2016-03/iOS-OpenGLES%E4%B9%8B%E5%9B%BE%E7%89%87%E7%BA%B9%E7%90%86/)以及对应的demo，运行结果发现图片只在左下角显示1/4，这是为什么？需要调整哪部分的代码才能填充整个viewport。
![wechatimg1](https://cloud.githubusercontent.com/assets/5006599/23015463/e754d170-f46d-11e6-89e8-9da7052534e8.jpeg)
![wechatimg2](https://cloud.githubusercontent.com/assets/5006599/23015464/e781a2b8-f46d-11e6-8608-38ff3e518d03.jpeg)

**Comment by SongJiaqiang** [comment]
找到原因了，glViewport设置渲染窗口的宽高时需要乘上屏幕的scale。
`let scale = UIScreen.main.scale`

**Comment by github4dogg** [comment]
感谢,解决了我的问题
